[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino

upload_port = COM9
monitor_port = COM9
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    jrowberg/I2Cdevlib-MPU6050@^1.0.0
    jrowberg/I2Cdevlib-Core@^1.0.0